INSERT INTO Action VALUES(1, 1, 'Saute du pont', true);
INSERT INTO Action VALUES(2, 1, 'Aller marcher dans la rue en sous-vêtements', true);
INSERT INTO Action VALUES(3, 1, 'Faire des pompes pendant 1 minute', true);
INSERT INTO Action VALUES(4, 2, 'Poster une photo ridicule sur Instagram', true);
INSERT INTO Action VALUES(5, 2, 'Faire une déclaration d’amour imaginaire', true);
INSERT INTO Action VALUES(6, 2, 'Parler avec un accent quebecois', true);
INSERT INTO Action VALUES(7, 1, 'Laisser un autre joueur vous maquiller', true);
INSERT INTO Action VALUES(8, 1, 'Danser sur une chanson des L5', true);
INSERT INTO Action VALUES(9, 3, 'Chanter une chanson de Céline Dion', true);
INSERT INTO Action VALUES(10, 3, 'Embrasser un autre joueur', true);
INSERT INTO Action VALUES(11, 3, 'Boire un shot d’alcool', true);

INSERT INTO Action VALUES(12, 3, 'Melange ton verre d’alcool avec celui des autres joueurs', true);
INSERT INTO Action VALUES(13, 3, 'Enlève tes vêtements et sort dans la rue', true);
INSERT INTO Action VALUES(14, 2, 'Laissez vos yeux se connecter et reconnaître un autre joueur à son odeur.', true);
INSERT INTO Action VALUES(15, 3, 'Enlevez vos chaussettes et tout ce qui se trouve dans votre pantalon et / ou votre soutien-gorge.', true);
INSERT INTO Action VALUES(16, 2, 'Echangez le t-shirt avec la personne à droite / à gauche de vous.', true);
INSERT INTO Action VALUES(17, 3, 'lèche le sol.', true);
INSERT INTO Action VALUES(18, 1, 'Nourrissez la personne à côté de vous avec quelque chose de savoureux.', true);
INSERT INTO Action VALUES(19, 1, 'Fais sentir tes chaussures à la personne de ton choix', true);
INSERT INTO Action VALUES(20, 1, 'Décrivez votre pire professeur actuel.', true);
INSERT INTO Action VALUES(21, 1, 'Imite un animal choisi par le groupe', true);
INSERT INTO Action VALUES(22, 1, 'Téléphone à une personne au hasard et dit lui qu’elle est joli.', true);
INSERT INTO Action VALUES(23, 1, 'Bois un verre d’eau chaude sans t’arrêter', true);
INSERT INTO Action VALUES(24, 2, 'Chante une chanson de ton choix en ayant la bouche pleine', true);
INSERT INTO Action VALUES(25, 2, 'Se comporter comme un poulet et faire des roulades à traver la piece', true);
INSERT INTO Action VALUES(26, 2, 'Déshabille toi et porte tes habits à l’envers dès maintenant', true);
INSERT INTO Action VALUES(27, 3, 'Bois 3 verres d’alcool à la suite', true);
INSERT INTO Action VALUES(28, 3, 'Deguste un aliment sucré mélangé à un aliment salé choisi par les autres joueurs', true);
INSERT INTO Action VALUES(29, 3, 'Fais le canard dans toute la maison', true);


INSERT INTO Verite VALUES(1, 1, true, 'Aimes tu mandiau ?');
INSERT INTO Verite VALUES(2, 1, true, 'Quelle est ta pire honte ?');
INSERT INTO Verite VALUES(3, 2, true, 'Quelle est ta pire bêtise étant enfant ?');
INSERT INTO Verite VALUES(4, 2, true, 'Quel est ton rêve le plus bizarre');
INSERT INTO Verite VALUES(5, 2, true, 'Il te reste 24h à vivre, qu’est-ce que tu fais ?');
INSERT INTO Verite VALUES(6, 1, true, 'Quel est le pire cadeau qu’on t’a offert ?');
INSERT INTO Verite VALUES(7, 1, true, 'Tu as une technique de drague secrète ?');
INSERT INTO Verite VALUES(8, 1, true, 'Quel le pire mensonge que tu as raconté ?');
INSERT INTO Verite VALUES(9, 3, true, 'Tu as un complexe ?');
INSERT INTO Verite VALUES(10, 3, true, 'Est-ce que tu ronfles ?');
INSERT INTO Verite VALUES(11, 1, true, 'Est-ce que tu as déjà rembourré ton soutif ou ton slip ?');
INSERT INTO Verite VALUES(12, 1, true, 'Quel est ton plus grand secret ?');
INSERT INTO Verite VALUES(13, 1, true, 'Si tu pouvais changer quelque chose dans ton corps, qu’est-ce que ce serait ?');
INSERT INTO Verite VALUES(14, 3, true, 'Tu préfères Qu’on t’enfonce une aiguille sur chaque oeil OU Qu’on te coupe tes oreilles');
INSERT INTO Verite VALUES(15, 1, true, 'Cite 3 qualités de ton voisin de gauche');
INSERT INTO Verite VALUES(16, 2, true, 'Cite 3 défauts de ton voisin de droite');
INSERT INTO Verite VALUES(17, 3, true, 'Avec quelle personne présente ici aimerais-tu prendre un bain ?');
INSERT INTO Verite VALUES(18, 3, true, 'As-tu déjà embrassé une personne du même sexe ?');
INSERT INTO Verite VALUES(19, 1, true, 'As-tu déjà menti à ce jeu ?');
INSERT INTO Verite VALUES(20, 2, true, 'Quel type de vêtement du sexe opposé aimerais-tu porter ?');
INSERT INTO Verite VALUES(21, 3, true, 'Es-tu déjà sorti avec plusieurs personnes en même temps ?');
INSERT INTO Verite VALUES(22, 2, true, 'Quelle a été sa plus grosse cuite?');
INSERT INTO Verite VALUES(23, 3, true, 'Raconte une histoire drôle à propos de l''un(e) de tes ex?');
INSERT INTO Verite VALUES(24, 2, true, 'À quoi pensez-vous lorsque vous êtes assis sur les toilettes ?');
INSERT INTO Verite VALUES(25, 3, true, 'Vous êtes-vous déjà fait pipi dessus ?');
INSERT INTO Verite VALUES(26, 1, true, 'Qui aimez-vous le moins dans cette pièce et pourquoi ?');
INSERT INTO Verite VALUES(27, 2, true, 'Quel est le dernier message que vous avez envoyé ?');
INSERT INTO Verite VALUES(28, 2, true, 'Échangeriez-vous votre frère contre un million d’euros ?');
INSERT INTO Verite VALUES(29, 3, true, 'Quelle est cette chose que vous ne feriez jamais même si quelqu’un vous offrait tout l’argent du monde ?');
INSERT INTO Verite VALUES(30, 3, true, 'Qui dans la pièce serait un mauvais rencard, d’après vous ?');
INSERT INTO Verite VALUES(31, 1, true, 'Quelle est la chose la plus méchante que vous ayez faite dans votre vie ?');