INSERT INTO Action VALUES(1, 1, 'Saute du pont', true);
INSERT INTO Action VALUES(2, 1, 'Aller marcher dans la rue en sous-vêtements', true);
INSERT INTO Action VALUES(3, 1, 'Faire des pompes pendant 1 minute', true);
INSERT INTO Action VALUES(4, 2, 'Poster une photo ridicule sur Instagram', true);
INSERT INTO Action VALUES(5, 2, 'Faire une déclaration d’amour imaginaire', true);
INSERT INTO Action VALUES(6, 2, 'Parler avec un accent toute la soirée', true);
INSERT INTO Action VALUES(7, 1, 'Laisser un autre joueur vous maquiller', true);
INSERT INTO Action VALUES(8, 1, 'Danser sur une chanson des L5', true);
INSERT INTO Action VALUES(9, 3, 'Chanter une chanson de Céline Dion', true);
INSERT INTO Action VALUES(10, 3, 'Embrasser un autre joueur', true);
INSERT INTO Action VALUES(11, 3, 'Boire un shot d’alcool', true);

INSERT INTO Action VALUES(12, 3, 'Melange ton verre d’alcool avec celui des autres joueurs', true);
INSERT INTO Action VALUES(13, 3, 'Enlève tes vêtements et sort dans la rue', true);
INSERT INTO Action VALUES(14, 2, 'Laissez vos yeux se connecter et reconnaître un autre joueur à son odeur.', true);
INSERT INTO Action VALUES(15, 3, 'Enlevez toutes les chaussettes et tout ce qui se trouve dans votre pantalon et / ou votre soutien-gorge.', true);
INSERT INTO Action VALUES(16, 2 , 'Echangez le t-shirt avec la personne à droite / à gauche de vous.', true);
INSERT INTO Action VALUES(17, 3, 'lèche le sol.', true);
INSERT INTO Action VALUES(18, 1, 'Nourrissez la personne à côté de vous avec quelque chose de savoureux.', true);
INSERT INTO Action VALUES(19, 1, 'Fais sentir tes chaussures à la personne de ton choix', true);
INSERT INTO Action VALUES(20, 1, 'Décrivez votre pire professeur actuel.', true);

INSERT INTO Verite VALUES(1, 1, true, 'Aimes tu mandiau ?');
INSERT INTO Verite VALUES(2, 1, true, 'Quelle est ta pire honte ?');
INSERT INTO Verite VALUES(3, 2, true, 'Quelle est ta pire bêtise étant enfant ?');
INSERT INTO Verite VALUES(4, 2, true, 'Quel est ton rêve le plus bizarre');
INSERT INTO Verite VALUES(5, 2, true, 'Il te reste 24h à vivre, qu’est-ce que tu fais ?');
INSERT INTO Verite VALUES(6, 1, true, 'Quel est le pire cadeau qu’on t’a offert ?');
INSERT INTO Verite VALUES(7, 1, true, 'Tu as une technique de drague secrète ?');
INSERT INTO Verite VALUES(8, 1, true, 'Quel le pire mensonge que tu as raconté ?');
INSERT INTO Verite VALUES(9, 3, true, 'Tu as un complexe ?');
INSERT INTO Verite VALUES(10, 3, true, 'Est-ce que tu ronfles ?');
INSERT INTO Verite VALUES(11, 1, true, 'Est-ce que tu as déjà rembourré ton soutif ou ton slip ?');
INSERT INTO Verite VALUES(12, 1, true, 'Quel est votre plus grand secret ?');
INSERT INTO Verite VALUES(13, 1, true, 'Si tu pouvais changer quelque chose dans ton corps, qu’est-ce que ce serait ?');
INSERT INTO Verite VALUES(14, 3, true, 'Tu préfères Qu’on t’enfonce une aiguille sur chaque oeil OU Qu’on te coupe tes oreilles');
INSERT INTO Verite VALUES(15, 1, true, 'Cite 3 qualités de ton voisin de gauche');
INSERT INTO Verite VALUES(16, 2, true, 'Cite 3 défauts de ton voisin de droite');
INSERT INTO Verite VALUES(17, 3, true, 'Avec quelle personne présente ici aimerais-tu prendre un bain ?');
INSERT INTO Verite VALUES(18, 3, true, 'As-tu déjà embrassé une personne du même sexe ?');
INSERT INTO Verite VALUES(19, 1, true, 'As-tu déjà menti à ce jeu ?');
INSERT INTO Verite VALUES(20, 2, true, 'Quel type de vêtement du sexe opposé aimerais-tu porter ?');
INSERT INTO Verite VALUES(21, 3, true, 'Es-tu déjà sorti avec plusieurs personnes en même temps ?');